### ISSUE TITLE
Vertical Movement

### ISSUE THREAD

**Issue by nishabe** [yorkhackspace/meArm#3]
Hello Team,
In my mearm (bigger) set up I could not make a vertical straight line movement.
I also see a forward movement even though there is no change in Y axis.
Default co-ordinate in library: (0,120,120)
Starting point: (0,120,120)
Endpoint : (0,120,50)

What was your experience with vertical movement?
Please see the video.
https://youtu.be/ke-cWWhMrG4

**Comment by jdavo** [comment]
That video is private and I am unable to view it.

**Comment by nishabe** [comment]
Changed, the URL. Thanks.

**Comment by aquila12** [comment]
We've not previously seen an issue like this; are you sure your arm lengths (in particular L1 and L2) are correct?

Is the shoulder servo able to turn enough to provide a straight up and down movement (i.e, can the first section of the arm move backward from where it is in the video)?

**Comment by nishabe** [comment]
Answers to your questions:
1) 
The arm lengths are as below:
L1 : 160
L2 : 160
L3 : 95. (i.e,10+85)
Also I have made a small change in meArm.cpp, function: 'begin' as below:
  //goDirectlyToCylinder(0, 100, 50); Original Values
  goDirectlyToCylinder(0, 190, 200);

The default position has been made equivalent of the start position in the sketch in order to avoid shake when the app start the execution.
2) The shoulder is able to turn enough to provide straight up and down movement.

Here is a video after doing some calibration. You can see a slight deviation in the Y axis.
https://youtu.be/42m7BpRDzl4

Below is the sketch that which was running:

#include <fk.h>
#include <ik.h>
#include <meArm.h>
#include <Servo.h>

int gripperPin = 6;
int elbowPin = 9; // Left
int shoulderPin = 10; // Right
int basePin = 11;
meArm arm(
      173,24, -pi/2, pi/2,    //Base     (-90 to  90 degrees)
      178,50, pi/4, 3*pi/4,   //Shoulder ( 45 to 135 degrees)
      178,73, 0, -pi/4,      //Elbow    (  0 to -45 degrees)
      55,136, pi/2, 0);        //Gripper  ( 90 to   0 degrees)

void setup() {
  arm.begin(basePin, shoulderPin, elbowPin, gripperPin);
}

void loop() {
    int startingXPos=0;
    int startingYPos=190;
    int startingZPos=200;
    int endingZPos=120;
  // Going Down
  arm.gotoPoint(startingXPos,startingYPos,endingZPos);
  delay(2000);  
  // Going Up  
  arm.gotoPoint(startingXPos,startingYPos,startingZPos);
  delay(2000);
}

**Comment by aquila12** [comment]
I'm not quite sure what's happening there; I've run a quick test using your values and it is showing a slight movement in the shoulder between those positions.  One thing that might be worth checking is your servo calibrations; they look a bit odd for the angles.  For most servos, the difference between the calibration values should be in the same region as the angle swept (in degrees) in the comment.

So, I'd expect the base servo to have a range of around 180 degrees, the shoulder around 90 degrees (currently calibrated at 45 degrees forward and backward - possibly with the linkage removed), and the elbow around 45 degrees (currently calibrated horizontal and 45 degrees downward).  Your current servos look like they're calibrated for ~150deg, ~128deg and ~105deg, respectively, which seem a little far from the "ideal" case (there is some degree of variation in servos, but I'd expect that to be less pronounced).

The good positions to calibrate are base at 90 degrees left and right of centre, shoulder 45 degrees forward and backward of vertical, and (with shoulder vertical) elbow level and dropped 45 degrees.

A quick sketch using the Servo library should make this relatively easy - adjust the values you feed in and take a note of the values at each of those positions.  Those then form your calibration values.

Let me know how you get on.

**Comment by nishabe** [comment]
Hi Nick,
Thank you very much for your suggestions which proved to be correct in this case.
I re-visited the calibration steps as explained here (http://bitofahack.com/post/1433701488) and there were some mistakes in the way I did it earlier.
With the new values, the movement is lot better.
Here is the final movement : https://youtu.be/o10n0FalmeA
Thanks, again.

**Comment by aquila12** [comment]
That's great to hear - and it looks a lot better!

One thing that might need revisiting in future is the conversion of angles into servo pulsewidths - at the moment, the conversion is being done twice: once from radians to degrees, by our code, and then from degrees to microseconds, in the servo library.  As the two latter measurements are done as integers, there will be greater rounding errors, which we might be able to eliminate.

**Comment by nishabe** [comment]
Love to see that enhancement soon!
:+1:
